### ISSUE TITLE
초기 개발 환경 설정

### ISSUE THREAD

**Issue by mizuirohoshi7** [mizuirohoshi7/budget-guard#1]
## 📝 Description

필요한 의존성을 추가하고 예외 처리 및 Api 응답 포맷을 설정합니다.

## ☑️ TODO

- [x] p6spy 의존성 추가
- [x] jjwt 의존성 추가
- [x] querydsl 의존성 추가
- [ ] 전역 예외 처리
- [x] ApiResponse 생성
